// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehluzcvzntavfgiugdxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVobHV6Y3Z6bnRhdmZnaXVnZHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MjE3NjYsImV4cCI6MjA3NTA5Nzc2Nn0.-a0j7owdaDRiZXwMy0drq6Qj30rShaFv_ofhHtjKf-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});